#!/usr/bin/env bash
# CODE SHIELD V3 -- Stage 2: User Isolation & Secret Migration
# Sourced by install.sh -- do not execute directly.

info "Configuring user isolation and secret migration ..."

SECRETS_FILE="$CS_CONF_DIR/secrets.env"
OPENCLAW_HOME="/home/openclaw"
OPENCLAW_SVC_HOME="/var/lib/openclaw-svc"
OPENCLAW_JSON="$OPENCLAW_HOME/.openclaw/openclaw.json"
DROPIN_DIR="/etc/systemd/system/openclaw.service.d"
DROPIN_FILE="$DROPIN_DIR/codeshield.conf"

###############################################################################
# 1. Ensure openclaw-svc user exists
###############################################################################
if ! id "openclaw-svc" &>/dev/null; then
    if [ "$DRY_RUN" -eq 1 ]; then
        info "[DRY-RUN] Would create user openclaw-svc"
    else
        useradd --system --shell /usr/sbin/nologin \
                --home-dir "$OPENCLAW_SVC_HOME" \
                --create-home openclaw-svc
        ok "Created system user: openclaw-svc"
    fi
else
    ok "User openclaw-svc already exists."
fi

###############################################################################
# 2. Ensure openclaw-svc is NOT in docker or sudo groups
###############################################################################
if [ "$DRY_RUN" -eq 0 ]; then
    for grp in docker sudo; do
        if id -nG openclaw-svc 2>/dev/null | grep -qw "$grp"; then
            gpasswd -d openclaw-svc "$grp" 2>/dev/null || true
            warn "Removed openclaw-svc from $grp group."
        fi
    done
    ok "openclaw-svc group isolation verified."
fi

###############################################################################
# 3. Migrate inline secrets from openclaw.json to secrets.env
###############################################################################
migrate_secrets() {
    if [ ! -f "$OPENCLAW_JSON" ]; then
        warn "openclaw.json not found at $OPENCLAW_JSON -- skipping migration."
        return 0
    fi

    info "Scanning openclaw.json for inline secrets ..."

    local changed=0
    # List of keys that should be externalized
    local secret_keys=("telegramBotToken" "braveApiKey" "openaiApiKey" "gatewayToken" "qdrantApiKey")
    local env_names=("TELEGRAM_BOT_TOKEN" "BRAVE_API_KEY" "OPENAI_API_KEY" "OPENCLAW_GATEWAY_TOKEN" "QDRANT_API_KEY")

    for i in "${!secret_keys[@]}"; do
        local jkey="${secret_keys[$i]}"
        local ekey="${env_names[$i]}"
        local jval
        jval=$(jq -r ".$jkey // empty" "$OPENCLAW_JSON" 2>/dev/null || true)

        if [ -n "$jval" ] && [ "$jval" != "null" ]; then
            info "Found inline secret: $jkey -> migrating to secrets.env"
            # Update secrets.env if the key exists; append if not
            if grep -q "^${ekey}=" "$SECRETS_FILE" 2>/dev/null; then
                sed -i "s|^${ekey}=.*|${ekey}=${jval}|" "$SECRETS_FILE"
            else
                echo "${ekey}=${jval}" >> "$SECRETS_FILE"
            fi
            # Blank out in openclaw.json
            local tmp
            tmp=$(jq ".$jkey = \"\"" "$OPENCLAW_JSON")
            echo "$tmp" > "$OPENCLAW_JSON"
            changed=1
        fi
    done

    if [ "$changed" -eq 1 ]; then
        chmod 0600 "$SECRETS_FILE"
        chown root:root "$SECRETS_FILE"
        ok "Secrets migrated from openclaw.json to secrets.env"
    else
        ok "No inline secrets found in openclaw.json."
    fi
}

if [ "$DRY_RUN" -eq 0 ]; then
    migrate_secrets
fi

###############################################################################
# 4. Sync openclaw data to openclaw-svc home
###############################################################################
if [ "$DRY_RUN" -eq 0 ]; then
    mkdir -p "$OPENCLAW_SVC_HOME/.openclaw"
    if [ -d "$OPENCLAW_HOME/.openclaw" ]; then
        rsync -a --update "$OPENCLAW_HOME/.openclaw/" "$OPENCLAW_SVC_HOME/.openclaw/" 2>/dev/null || \
            cp -a "$OPENCLAW_HOME/.openclaw/"* "$OPENCLAW_SVC_HOME/.openclaw/" 2>/dev/null || true
        chown -R openclaw-svc:openclaw-svc "$OPENCLAW_SVC_HOME/.openclaw"
        ok "Synced openclaw data to $OPENCLAW_SVC_HOME/.openclaw"
    else
        warn "No openclaw data directory found to sync."
    fi
fi

###############################################################################
# 5. Create systemd drop-in for environment injection
###############################################################################
if [ "$DRY_RUN" -eq 1 ]; then
    info "[DRY-RUN] Would create drop-in at $DROPIN_FILE"
else
    mkdir -p "$DROPIN_DIR"
    cat > "$DROPIN_FILE" << 'DROPIN_EOF'
# CODE SHIELD V3 -- systemd drop-in for openclaw.service
# Injects externalized secrets via EnvironmentFile
# This file is regenerated by codeshield-guardian after updates.
[Service]
User=openclaw-svc
Group=openclaw-svc
EnvironmentFile=/etc/openclaw-codeshield/secrets.env

# Security hardening
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=read-only
PrivateTmp=yes
ReadWritePaths=/var/lib/openclaw-svc
DROPIN_EOF

    chmod 0644 "$DROPIN_FILE"
    systemctl daemon-reload 2>/dev/null || true
    ok "Created systemd drop-in: $DROPIN_FILE"
fi

###############################################################################
# 6. Controlled sudoers for openclaw-svc
###############################################################################
SUDOERS_FILE="/etc/sudoers.d/openclaw-codeshield"
if [ "$DRY_RUN" -eq 0 ]; then
    cat > "$SUDOERS_FILE" << 'SUDOERS_EOF'
# CODE SHIELD V3 -- Controlled sudo for openclaw-svc
# Only allow restarting its own service
openclaw-svc ALL=(root) NOPASSWD: /usr/bin/systemctl restart openclaw.service
openclaw-svc ALL=(root) NOPASSWD: /usr/bin/systemctl status openclaw.service
SUDOERS_EOF
    chmod 0440 "$SUDOERS_FILE"
    visudo -cf "$SUDOERS_FILE" &>/dev/null || {
        fail "Sudoers file syntax error! Removing."
        rm -f "$SUDOERS_FILE"
    }
    ok "Controlled sudoers installed: $SUDOERS_FILE"
fi

ok "User isolation and secret migration complete."
